services:
  postgres:
    image: postgres:17.4
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledgedb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  knowledge-base:
    image: knowledge-base:latest
    build: .
    restart: "no"
    ports:
      - "8085:8080"

volumes:
  postgres_data: