services:
  postgres:
    image: postgres:17.4
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledgedb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  knowledge-base:
    image: knowledge-base:latest
    build: .
    restart: "no"
    ports:
      - "8085:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/knowledgedb  # Переопределяем для Docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - c:/export:/export  # Монтируем e:/export в /export внутри контейнера

volumes:
  postgres_data: