spring:
  application:
    name: knowledge-base

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/knowledgedb}  # По умолчанию localhost
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      schema: knowledgedb_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS knowledgedb_schema
      connection-timeout: 10000

server:
  port: 8080

parser:
  input-file-path: "e:/Основы Backend-разработки-chg.md"
  output-file-path: "e:/exported_md/"
  theme: "Backend-разработка"